### ISSUE TITLE
Download CI Build of package ch.fhir.ig.ch-epl

### ISSUE THREAD

**Issue by snowping** [bag-epl/bag-epl-fhir#5]
Since the fhir package is not officially published yet. Where can I download the CI build for the package [ch.fhir.ig.ch-epl#0.1.0](https://simplifier.net/packages/ch.fhir.ig.ch-epl/0.1.0)?

I try to test it via the Firely .NET SDK. My intension is to load the extensions into my code base using the following method (via Firely.Fhir.Packages):

```
var release = FhirRelease.R5;
FhirPackageSource packageSource = new(new ModelInspector(release), "fhir/packages/ch.fhir.ig.ch-ep.tgz");
var extension = await packageSource!.ResolveByCanonicalUriAsync("http://fhir.ch/ig/ch-epl/StructureDefinition/regulatedAuthorization-limitation");
```

Could someone give me a hint?

**Comment by ziegm** [comment]
You can download the package locally from the ci build:
https://build.fhir.org/ig/bag-epl/bag-epl-fhir/branches/master/index.html
-> there is a download link: Download: You can download this implementation guide in the [npm format](https://confluence.hl7.org/display/FHIR/NPM+Package+Specification) from [here](https://build.fhir.org/ig/bag-epl/bag-epl-fhir/branches/master/package.tgz).

Does that help?

**Comment by snowping** [comment]
> You can download the package locally from the ci build: https://build.fhir.org/ig/bag-epl/bag-epl-fhir/branches/master/index.html -> there is a download link: Download: You can download this implementation guide in the [npm format](https://confluence.hl7.org/display/FHIR/NPM+Package+Specification) from [here](https://build.fhir.org/ig/bag-epl/bag-epl-fhir/branches/master/package.tgz).
> 
> Does that help?

awesome, yes! That helps. I've overseen those links.
